[#951] Publish all release NPM and Python packages to NPM and PyPi
legion-platform/legion-mlflow pull request #6
Opened 2019-11-07 06:40 UTC by vlad-tokarev

#951

2019-11-07 11:04 UTC, mcdoker18 requested changes

2019-11-07 11:04 UTC, mcdoker18 commented on setup.py
> +    name='legion_mlflow_runner-test',
Please, fix the name `legion_mlflow_runner` -> `legion-mlflow-runner`

2019-11-07 11:04 UTC, mcdoker18 commented on setup.py
> +        f'legion-sdk=={extract_version()}',
I think It will not work with a dev version.

2019-11-07 11:04 UTC, mcdoker18 commented on scripts/Jenkinsfile
> +            pythonAlpinePath = "legion-cicd/containers/python-alpine"
I don't like that all our build pipelines know the paths of `ci-cd` repository. `legionPipeline.groovy` is an exception.
Why we can't hardcode these parameters in the `legionPipeline.groovy` script?

2019-11-07 11:04 UTC, mcdoker18 commented on scripts/Jenkinsfile
> +                                    print("Publishing packages to public registry skipped – publishing option is disabled")
We should push in the nexus for every build and pypi\npm\... for every *stable* release.

2019-11-08 05:42 UTC, mcdoker18 approved these changes

2019-11-08 06:12 UTC, kirillmakhonin reviewed
I guess we should not publish internal domains

2019-11-08 07:26 UTC, maxkochubey approved these changes

2019-11-08 08:32 UTC, vlad-tokarev commented
> I guess we should not publish internal domains

What exactly do you mean? Give a reference plz

2019-11-08 09:36 UTC, merged